token: "xxxxxxxxxxxxxxxxxxx"
url: "https://lichess.org/"

engine:
  dir: "../python/"
  name: "engine.py"

  working_dir: ""
  protocol: "uci"
  ponder: true

  polyglot:
    enabled: false
    book:
      standard:
        - engines/book1.bin
        - engines/book2.bin
    min_weight: 1
    selection: "weighted_random"
    max_depth: 20

  draw_or_resign:
    resign_enabled: false
    resign_score: -1000
    resign_for_egtb_minus_two: true
    resign_moves: 3
    offer_draw_enabled: true
    offer_draw_score: 0
    offer_draw_for_egtb_zero: true
    offer_draw_moves: 10
    offer_draw_pieces: 10

  online_moves:
    max_out_of_book_moves: 10
    max_retries: 2
    max_depth: 5
    chessdb_book:
      enabled: false
    lichess_cloud_analysis:
      enabled: false
    lichess_opening_explorer:
      enabled: true
      min_time: 20
      source: "masters"
      player_name: ""
      sort: "games_played"
      min_games: 50
    online_egtb:
      enabled: true
      min_time: 0.1
      max_pieces: 5
      source: "lichess"
      move_quality: "best"
  lichess_bot_tbs:
    syzygy:
      enabled: false
      paths:
        - "engines/syzygy"
      max_pieces: 7
      move_quality: "best"

# engine_options:                  # Any custom command line params to pass to the engine.
#   cpuct: 3.1

  homemade_options:
#   Hash: 256

  uci_options:
    Move Overhead: 100
#   go_commands:
#     nodes: 1
#     depth: 5
#     movetime: 1000

  silence_stderr: false

abort_time: 30
fake_think_time: false
rate_limiting_delay: 100
move_overhead: 2000
max_takebacks_accepted: 0
quit_after_all_games_finish: false

correspondence:
  move_time: 60  
  checkin_period: 300
  disconnect_time: 150
  ponder: false

challenge:
  concurrency: 1
  sort_by: "first"
  preference: "none"
  accept_bot: true
  only_bot: false
  max_increment: 20
  min_increment: 0
  max_base: 600
  min_base: 0
  max_days: 14 
  min_days: 1
  variants:
    - standard
  time_controls:
    - bullet
    - blitz
    - rapid
  modes: 
    - casual
    - rated
  bullet_requires_increment: false
  max_simultaneous_games_per_user: 1

greeting:
  # Optional substitution keywords (include curly braces):
  #   {opponent} to insert opponent's name
  #   {me} to insert bot's name
  hello: "Hi! I'm PikoZero. Good luck."
  goodbye: "Good game!"
  hello_spectators: "Hi! I'm PikoZero."
  goodbye_spectators: "Thanks for watching!"

matchmaking:
  allow_matchmaking: true
  allow_during_games: false 
  challenge_variant: "random"
  challenge_timeout: 1
  challenge_initial_time:
    - 60
    - 180
  challenge_increment: 
    - 1
    - 2
  opponent_rating_difference: 300
  rating_preference: "none"
  challenge_mode: "rated"
  challenge_filter: none
  include_challenge_block_list: false
