[DEFAULT]
model_size = lg
project_dir = /home/tomaz/ChessBot_v2
restore_dir = /home/tomaz/ChessBot_v2_trash

# Model
# History
history_steps = 8
history_perspective_flip = false
history_repetition_planes = 1

# Actionspace
actionspace_size = 1858

#MCTS
## Root exploration noise
root_dirichlet_alpha = 0.3
root_exploration_fraction = 0.25

## Fpu
fpu_root = 1.0
fpu_leaf = 0.3

## UCB constants
pb_c_base = 19652
pb_c_init = 2.5
pb_c_factor = 1.0

## Temperatures
moves_softmax_temp = 0.0
policy_temp = 1.0

num_vl_searches = 16

[training]
batch_size = 1024
# Only 70% of samples are used to prevent overfitting, 10% of those are used for validation
sampling_ratio = 0.7
validation_ratio = 0.1
learning_rate = 0.004
max_epochs_per_cycle = 500
# 2400
checkpoint_interval = 5000
# 480
sts_test_interval = 1000
sts_time_limit = 1.0
# 6 for sm & 3 for xl
sts_num_actors = 5
save_used_samples = true

[selfplay]
buffer_size = 10000
root_exploration_noise = true
num_mcts_sims = 800
num_mcts_sampling_moves = 30
moves_softmax_temp = 1.35

[engineplay]
root_exploration_noise = false
num_mcts_sampling_moves = 0
moves_softmax_temp = 0.0
