[DEFAULT]
model_size = sm
project_dir = /home/tomaz/ChessBot_v2/

# Model
# History
history_steps = 8
history_perspective_flip = false
history_repetition_planes = 1

# Actionspace
actionspace_size = 1858

#MCTS
## Root exploration noise
root_dirichlet_alpha = 0.3
root_exploration_fraction = 0.25

## Fpu
fpu_root = 1.0
fpu_leaf = 0.3

## UCB constants
pb_c_base = 19652
pb_c_init = 1.25
pb_c_factor = 1.0

## Temperatures
moves_softmax_temp = 0.0
policy_temp = 1.0

num_vl_searches = 16

[training]
batch_size = 1024

[selfplay]
batch_size = 16
root_exploration_noise = true
num_mcts_sims = 800
num_mcts_sampling_moves = 30
moves_softmax_temp = 1.0
