[package]
name = "rchess"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.pyo3]
version = "0.23.2"
features = ["auto-initialize"]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false
